language: node_js
node_js:
- '8.4'
notifications:
  slack:
    secure: blJ5TnfiOcBaahMcpctBF5p3wq6Nwy4m1hbCW2qA+1XmcR5ZMIM7I0Msq+WbcobX8SGTR6mM1kAd79Y18YItlifjQJB+5ld7jUDTo/EmDaBgviuylTa8V2/y9KaaJyQd9aK6FFdHrSqpQ0uAK6VbglblQAdDCfz7c2GBfQIMOeevutIbwzxo5eNZh7HlsLsPXkK1S3JXwZ7FIGDd5xbuMstyzKKOZPjJsixmdEduAZbmsKca80QurkukltOxNnGxU2msLKkwgpCCm4ZXrO3Td1pzXL0sD0gi18itqjiA2IEkoJvln+NLGKivabzfaVAcVG2ojdg7i9TFPyNHEYIzdeV5Hjghj1nehIGGxBTspGA1aU+m+mgdm3guex/P/ajTcbu0us0kHaGxgvdH4Wh1HqJqEI+KJBkdUCgCBxtnZ5ShZ/qefLk0CNyV1IoKBQeDAhwgtipw2bwS6jZn4i7zjcvytWr5ygGN9NMvT06hLTGh785CY6iPW7DiMGSHfqW4TtKSrIpBqqxLT7mDn3NvP7te3A/G9gjV4BGsW8K9JcTj07r5LE1GTGwQ0c17JC1B3jcdDVlfXMPqz2PviqbKim8DmG+lVoyzQ19eFuabYr3k8CuB0YwwXcOMGW3gqn2c7Nwx5JuVKLp1oUWtAr2Fm3qT7Rhgvde4xDZf4acNQNI=
  on_success: never
  on_failure: always